---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: media
  name: qbittorrent-prune
spec:
  schedule: "*/30 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: qbittorrent-prune
            image: onedr0p/qbittorrent-prune:v3.0.1
            imagePullPolicy: IfNotPresent
          env:
          - name: QB_URL
            value: "http://qbittorrent:8080"
          - name: QB_USERNAME
            valueFrom:
              secretKeyRef:
                name: qbittorrent
                key: username
          - name: QB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qbittorrent
                key: password
          - name: QB_CATEGORIES
            value: "sonarr,radarr"
          - name: LOG_LEVEL
            value: "2"
          - name: DRY_RUN
            value: "true"
